# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created: Thu Nov 15 09:45:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 723)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.LL = QtGui.QPushButton(self.groupBox_3)
        self.LL.setObjectName(_fromUtf8("LL"))
        self.horizontalLayout_4.addWidget(self.LL)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.LLBG = QtGui.QPushButton(self.groupBox_4)
        self.LLBG.setObjectName(_fromUtf8("LLBG"))
        self.horizontalLayout_5.addWidget(self.LLBG)
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.filterL = QtGui.QComboBox(self.groupBox_6)
        self.filterL.setObjectName(_fromUtf8("filterL"))
        self.filterL.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.filterL)
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.LS = QtGui.QPushButton(self.groupBox_7)
        self.LS.setObjectName(_fromUtf8("LS"))
        self.verticalLayout_3.addWidget(self.LS)
        self.horizontalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.LSBG = QtGui.QPushButton(self.groupBox_9)
        self.LSBG.setObjectName(_fromUtf8("LSBG"))
        self.verticalLayout_4.addWidget(self.LSBG)
        self.horizontalLayout_3.addWidget(self.groupBox_9)
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.filterS = QtGui.QComboBox(self.groupBox_8)
        self.filterS.setObjectName(_fromUtf8("filterS"))
        self.filterS.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.filterS)
        self.horizontalLayout_3.addWidget(self.groupBox_8)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.BTsave = QtGui.QPushButton(self.centralwidget)
        self.BTsave.setObjectName(_fromUtf8("BTsave"))
        self.verticalLayout.addWidget(self.BTsave)
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.filters = QtGui.QTableWidget(self.groupBox_5)
        self.filters.setObjectName(_fromUtf8("filters"))
        self.filters.setColumnCount(2)
        self.filters.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.filters.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.filters.setHorizontalHeaderItem(1, item)
        self.gridLayout.addWidget(self.filters, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Light reference", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.LL.setText(QtGui.QApplication.translate("MainWindow", "Load SIF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.LLBG.setText(QtGui.QApplication.translate("MainWindow", "Load SIF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterL.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "DF Measurement", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.LS.setText(QtGui.QApplication.translate("MainWindow", "Load SIF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.LSBG.setText(QtGui.QApplication.translate("MainWindow", "Load SIF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Filter", None, QtGui.QApplication.UnicodeUTF8))
        self.filterS.setItemText(0, QtGui.QApplication.translate("MainWindow", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.BTsave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Filters", None, QtGui.QApplication.UnicodeUTF8))
        item = self.filters.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Filter Name", None, QtGui.QApplication.UnicodeUTF8))
        item = self.filters.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Filter SIF File", None, QtGui.QApplication.UnicodeUTF8))

